#!/bin/bash
ROOT="$(dirname "$(dirname "$0")")"
cd "$ROOT"

dirs=(
  "src/app/(auth)/login"
  "src/app/(auth)/register"
  "src/app/(dashboard)/admin"
  "src/app/(dashboard)/analytics"
  "src/app/(dashboard)/users/[id]"
  "src/app/(dashboard)/orders/[id]"
  "src/app/(dashboard)/components"
  "src/components/ui/Button"
  "src/components/ui/Badge"
  "src/components/ui/Avatar"
  "src/components/ui/Spinner"
  "src/components/ui/Progress"
  "src/components/ui/Alert"
  "src/components/ui/Skeleton"
  "src/components/ui/EmptyState"
  "src/components/ui/Modal"
  "src/components/ui/Drawer"
  "src/components/ui/Tooltip"
  "src/components/ui/Tabs"
  "src/components/ui/Accordion"
  "src/components/ui/Dropdown"
  "src/components/ui/Breadcrumbs"
  "src/components/ui/CommandPalette"
  "src/components/ui/NotificationBell"
  "src/components/ui/ThemeToggle"
  "src/components/ui/Input"
  "src/components/ui/Textarea"
  "src/components/ui/Select"
  "src/components/ui/Checkbox"
  "src/components/ui/RadioGroup"
  "src/components/ui/Toggle"
  "src/components/ui/DateRangePicker"
  "src/components/ui/Card"
  "src/components/ui/StatCard"
  "src/components/ui/TextCard"
  "src/components/ui/ImageCard"
  "src/components/ui/Stepper"
  "src/components/ui/Timeline"
  "src/components/layout/Sidebar"
  "src/components/layout/Header"
  "src/components/charts/LineChart"
  "src/components/charts/BarChart"
  "src/components/charts/AreaChart"
  "src/components/charts/PieChart"
  "src/components/charts/DonutChart"
  "src/components/tables/DataTable"
  "src/components/tables/ExportButton"
  "src/contexts"
  "src/data"
  "src/hooks"
  "src/lib"
  "src/styles"
  "src/types"
  "src/tests/e2e"
  ".storybook"
)

for d in "${dirs[@]}"; do
  mkdir -p "$d"
done

echo "All directories created"
